default:
  bucket: 'databrew.org'
  server_name: 'https://databrew.org'
  target:
  - key: 'icf_verification'
    s3uri: 'metadata/icf_metadata.zip'
    fid: 'sepk_icf_verification'
    fs:
      - 'icf_metadata/individual_data.csv'
  - key: 'icf_resolution'
    s3uri: 'metadata/icf_metadata.zip'
    fid: 'sepk_icf_resolution'
    fs:
     - 'icf_metadata/individual_data.csv'
  - key: 'lab1'
    s3uri: 'metadata/lab_metadata.zip'
    fid: 'lab'
    fs:
     - 'lab_metadata/lab_data.csv'
  - key: 'lab2'
    s3uri: 'metadata/lab_metadata.zip'
    fid: 'lab2'
    fs:
     - 'lab_metadata/lab_data.csv'
develop:
  secret_name: 'test/odk-credentials'
  pid: 23
production:
  secret_name: 'prod/odk-credentials'
  pid: 15
