default:
  report_index:
    - v0
    - icf
    - ento
    - anomalies-detection
    - safety-efficacy
    - pharmacy
develop:
  report_index:
    - v0
    - icf
    - ento
    - anomalies-detection
    - safety-efficacy
    - pharmacy
