name: dockerhub-ci-anomaly-detection

on:
  push:
    branches:
      - 'main'
    paths:
      - anomaly-detection/**

jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./anomaly-detection
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Dockerfile
        run: docker build -f Dockerfile --progress=plain -t databrewllc/anomaly-detection:latest .
      - name: Push to Dockerhub
        run: docker push databrewllc/anomaly-detection:latest
