name: dockerhub-ci-odk-form-extraction

on: 
    push:
      paths:
        - odk-form-extraction/**

jobs:
  
  deploy-to-dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./odk-form-extraction
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Dockerfile based on commit sha
        run: docker build -f Dockerfile --progress=plain -t databrewllc/odk-form-extraction:develop .
      - name: Push to Dockerhub as latest
        run: docker push databrewllc/odk-form-extraction:develop
  
  deploy-to-prod:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./odk-form-extraction
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Dockerfile based on commit sha
        run: docker build -f Dockerfile --progress=plain -t databrewllc/odk-form-extraction:production .
      - name: Tag image based on commit SHA
        run: docker image tag databrewllc/odk-form-extraction:production databrewllc/odk-form-extraction:${GITHUB_SHA::7}
      - name: Push to Dockerhub with commit sha for version tracking
        run: docker push databrewllc/odk-form-extraction:${GITHUB_SHA::7}
      - name: Push to Dockerhub as latest
        run: docker push databrewllc/odk-form-extraction:production
