name: dockerhub-ci-pipeline-reporting
on:
    push:
      paths:
        - pipeline-reporting/**

jobs:

  deploy-to-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./pipeline-reporting
          push: true
          tags: databrewllc/pipeline-reporting:develop
          cache-from: type=registry,ref=databrewllc/pipeline-reporting:develop
          cache-to: type=inline

  deploy-to-prod:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pipeline-reporting
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Dockerfile based on commit sha
        run: docker build -f Dockerfile --progress=plain -t databrewllc/pipeline-reporting:production .
      - name: Tag image based on commit SHA
        run: docker image tag databrewllc/pipeline-reporting:production databrewllc/pipeline-reporting:${GITHUB_SHA::7}
      - name: Push to Dockerhub with commit sha for version tracking
        run: docker push databrewllc/pipeline-reporting:${GITHUB_SHA::7}
      - name: Push to Dockerhub as latest
        run: docker push databrewllc/pipeline-reporting:production
